import { z } from "zod";

import { CREATIVE_SKILL_IDS } from "./creative-skills.js";

const recordSchema = z.record(z.unknown());
const positionSchema = z.object({ x: z.number(), y: z.number() });
const viewportSchema = z.object({ x: z.number(), y: z.number(), k: z.number() });
const nodeTypeSchema = z.enum(["image", "text", "config", "video", "audio", "director"]);
const generationModeSchema = z.enum(["text", "image", "video", "audio"]);
const directorVectorSchema = z.tuple([z.number(), z.number(), z.number()]);
const directorLayerRoleSchema = z.enum(["background", "character", "prop", "foreground", "effect"]);
const directorAssetKindSchema = z.enum(["image", "video"]);
const directorAssetFitSchema = z.enum(["cover", "contain"]);
const directorPrimitiveSchema = z.enum(["character", "box", "sphere", "cylinder", "cone", "model", "image", "video"]);
const directorSceneSchema = z.object({
    version: z.union([z.literal(1), z.literal(2)]).optional(),
    name: z.string().optional(),
    duration: z.number().min(1).max(120).optional(),
    fps: z.number().min(12).max(60).optional(),
    aspectRatio: z.enum(["16:9", "9:16", "1:1", "4:3", "3:4"]).optional(),
    compositionMode: z.enum(["layers", "space3d"]).optional(),
    environment: z.enum(["studio", "courtyard", "mountain", "desert", "space"]).optional(),
    background: z.string().optional(),
    stage: z.object({
        showGrid: z.boolean().optional(),
        showGround: z.boolean().optional(),
        showLabels: z.boolean().optional(),
        scenePosition: directorVectorSchema.optional(),
        sceneRotation: directorVectorSchema.optional(),
        sceneScale: z.number().min(0.1).max(10).optional(),
        panoramaRotation: z.number().optional(),
        panoramaRadius: z.number().min(10).max(100).optional(),
        ambientIntensity: z.number().min(0).max(3).optional(),
    }).optional(),
    objects: z.array(z.object({
        id: z.string().optional(),
        name: z.string().optional(),
        primitive: directorPrimitiveSchema.optional(),
        position: directorVectorSchema.optional(),
        rotation: directorVectorSchema.optional(),
        scale: directorVectorSchema.optional(),
        color: z.string().optional(),
        modelUrl: z.string().optional(),
        storageKey: z.string().optional(),
        sourceNodeId: z.string().min(1).optional(),
        assetUrl: z.string().optional(),
        assetKind: directorAssetKindSchema.optional(),
        assetMimeType: z.string().optional(),
        assetWidth: z.number().positive().optional(),
        assetHeight: z.number().positive().optional(),
        displaySize: z.tuple([z.number().positive(), z.number().positive()]).optional(),
        fit: directorAssetFitSchema.optional(),
        role: directorLayerRoleSchema.optional(),
        layerOrder: z.number().optional(),
        opacity: z.number().min(0).max(1).optional(),
        visible: z.boolean().optional(),
        locked: z.boolean().optional(),
        backgroundProjection: z.enum(["backdrop", "panorama"]).optional(),
        characterRig: z.object({
            bodyPreset: z.enum(["male", "female", "strong", "slim", "child", "broad", "teen", "chibi"]).optional(),
            posePreset: z.enum(["stand", "t-pose", "walk", "run", "sit", "crouch", "kneel", "double-kneel", "fight", "hands-hips", "hook-punch", "kick", "think", "kick-ball", "throw", "bow", "wave", "arms-crossed", "phone", "point", "reach", "custom"]).optional(),
            height: z.number().min(0.5).max(1.8).optional(),
            width: z.number().min(0.55).max(1.8).optional(),
            joints: z.record(directorVectorSchema).optional(),
        }).optional(),
    }).passthrough()).max(80).optional(),
    cameras: z.array(z.object({ id: z.string().optional(), name: z.string(), position: directorVectorSchema, target: directorVectorSchema, fov: z.number().min(15).max(100).optional() })).max(24).optional(),
    shots: z.array(z.object({ id: z.string().optional(), name: z.string(), cameraId: z.string(), start: z.number(), end: z.number(), movement: z.enum(["static", "push-in", "pull-out", "pan-left", "pan-right", "orbit", "follow"]), description: z.string().optional() })).max(80).optional(),
    keyframes: z.array(z.object({ id: z.string().optional(), targetType: z.enum(["object", "camera"]), targetId: z.string(), property: z.enum(["position", "rotation", "scale", "target", "fov"]), time: z.number(), value: z.array(z.number()).min(1).max(3) })).max(800).optional(),
}).passthrough();

export const toolNames = [
    "site_navigate",
    "canvas_list_projects",
    "canvas_get_state",
    "canvas_get_selection",
    "canvas_get_node",
    "canvas_export_snapshot",
    "canvas_apply_ops",
    "canvas_create_node",
    "canvas_create_attachment_nodes",
    "canvas_create_text_node",
    "canvas_create_text_nodes",
    "canvas_create_config_node",
    "canvas_create_image_prompt_flow",
    "canvas_create_generation_flow",
    "canvas_create_director_scene",
    "canvas_update_director_scene",
    "canvas_export_director_prompt",
    "canvas_generate_text",
    "canvas_generate_image",
    "canvas_generate_video",
    "canvas_generate_audio",
    "canvas_update_node",
    "canvas_update_node_text",
    "canvas_move_nodes",
    "canvas_resize_node",
    "canvas_delete_nodes",
    "canvas_connect_nodes",
    "canvas_select_nodes",
    "canvas_set_viewport",
    "canvas_run_generation",
    "generation_get_status",
    "workbench_image_get_config",
    "workbench_image_generate",
    "workbench_video_get_config",
    "workbench_video_generate",
    "prompts_search",
    "assets_list",
    "assets_add",
    "creative_skills_list",
    "creative_skill_get",
] as const;
export type ToolName = (typeof toolNames)[number];

export const canvasOpSchema = z.discriminatedUnion("type", [
    z.object({ type: z.literal("add_node"), nodeType: nodeTypeSchema.optional(), id: z.string().optional(), title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), position: positionSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("update_node"), id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("delete_node"), id: z.string().optional(), ids: z.array(z.string()).optional() }).passthrough(),
    z.object({ type: z.literal("delete_connections"), id: z.string().optional(), ids: z.array(z.string()).optional(), all: z.boolean().optional() }).passthrough(),
    z.object({ type: z.literal("connect_nodes"), id: z.string().optional(), fromNodeId: z.string(), toNodeId: z.string() }).passthrough(),
    z.object({ type: z.literal("set_viewport"), viewport: viewportSchema }).passthrough(),
    z.object({ type: z.literal("select_nodes"), ids: z.array(z.string()) }).passthrough(),
    z.object({ type: z.literal("run_generation"), nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional() }).passthrough(),
]);

const textNodeSchema = z.object({
    text: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    width: z.number().optional(),
    height: z.number().optional(),
});

const generationOptionsSchema = z.object({
    model: z.string().optional(),
    size: z.string().optional(),
    quality: z.string().optional(),
    count: z.number().optional(),
    seconds: z.string().optional(),
    vquality: z.string().optional(),
    generateAudio: z.string().optional(),
    watermark: z.string().optional(),
    videoReferenceMode: z.enum(["ref", "first", "firstlast"]).optional(),
    audioVoice: z.string().optional(),
    audioFormat: z.string().optional(),
    audioSpeed: z.string().optional(),
    audioInstructions: z.string().optional(),
});

const generationFlowSchema = z.object({
    prompt: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    referenceNodeIds: z.array(z.string()).optional(),
});

export const toolInputSchemas = {
    site_navigate: z.object({ path: z.string() }),
    canvas_list_projects: z.object({ keyword: z.string().optional(), page: z.number().optional(), pageSize: z.number().optional() }),
    canvas_get_state: z.object({}).passthrough(),
    canvas_get_selection: z.object({}).passthrough(),
    canvas_get_node: z.object({ id: z.string() }),
    canvas_export_snapshot: z.object({}).passthrough(),
    canvas_apply_ops: z.object({ ops: z.array(canvasOpSchema) }),
    canvas_create_node: z.object({ nodeType: nodeTypeSchema, title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), metadata: recordSchema.optional() }),
    canvas_create_attachment_nodes: z.object({ attachmentIds: z.array(z.string()).min(1), x: z.number().optional(), y: z.number().optional(), gap: z.number().optional(), direction: z.enum(["row", "column"]).optional() }),
    canvas_create_text_node: z.object({ text: z.string().optional(), x: z.number().optional(), y: z.number().optional(), title: z.string().optional(), width: z.number().optional(), height: z.number().optional() }),
    canvas_create_text_nodes: z.object({ items: z.array(textNodeSchema).min(1), x: z.number().optional(), y: z.number().optional(), gap: z.number().optional(), direction: z.enum(["row", "column"]).optional() }),
    canvas_create_config_node: z.object({ prompt: z.string().optional(), mode: generationModeSchema.optional(), title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_create_image_prompt_flow: z.object({ prompt: z.string(), x: z.number().optional(), y: z.number().optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_create_generation_flow: generationFlowSchema.extend({ mode: generationModeSchema.optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_create_director_scene: z.object({ scene: directorSceneSchema, title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional() }),
    canvas_update_director_scene: z.object({ nodeId: z.string(), scene: directorSceneSchema, replace: z.boolean().optional(), title: z.string().optional() }),
    canvas_export_director_prompt: z.object({ nodeId: z.string(), title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional() }),
    canvas_generate_text: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_image: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_video: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_audio: generationFlowSchema.merge(generationOptionsSchema),
    canvas_update_node: z.object({ id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }),
    canvas_update_node_text: z.object({ id: z.string(), text: z.string().optional(), title: z.string().optional() }),
    canvas_move_nodes: z.object({ items: z.array(z.object({ id: z.string(), x: z.number().optional(), y: z.number().optional(), dx: z.number().optional(), dy: z.number().optional() })).min(1) }),
    canvas_resize_node: z.object({ id: z.string(), width: z.number(), height: z.number(), freeResize: z.boolean().optional() }),
    canvas_delete_nodes: z.object({ ids: z.array(z.string()).min(1) }),
    canvas_connect_nodes: z.object({ connections: z.array(z.object({ fromNodeId: z.string(), toNodeId: z.string() })).min(1) }),
    canvas_select_nodes: z.object({ ids: z.array(z.string()) }),
    canvas_set_viewport: z.object({ viewport: viewportSchema }),
    canvas_run_generation: z.object({ nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional() }),
    generation_get_status: z.object({ scope: z.enum(["all", "canvas", "image", "video"]).optional(), taskId: z.string().optional(), nodeIds: z.array(z.string()).optional(), limit: z.number().optional() }),
    workbench_image_get_config: z.object({}).passthrough(),
    workbench_image_generate: z.object({ prompt: z.string(), model: z.string().optional(), quality: z.string().optional(), size: z.string().optional(), count: z.number().optional(), run: z.boolean().optional() }),
    workbench_video_get_config: z.object({}).passthrough(),
    workbench_video_generate: z.object({ prompt: z.string(), model: z.string().optional(), size: z.string().optional(), seconds: z.string().optional(), resolution: z.string().optional(), generateAudio: z.boolean().optional(), watermark: z.boolean().optional(), run: z.boolean().optional() }),
    prompts_search: z.object({ keyword: z.string().optional(), category: z.string().optional(), tags: z.array(z.string()).optional(), page: z.number().optional(), pageSize: z.number().optional() }),
    assets_list: z.object({ kind: z.enum(["all", "text", "image", "video"]).optional(), keyword: z.string().optional(), page: z.number().optional(), pageSize: z.number().optional() }),
    assets_add: z.object({ kind: z.enum(["text", "image"]), title: z.string(), content: z.string().optional(), imageUrl: z.string().optional(), tags: z.array(z.string()).optional(), source: z.string().optional(), note: z.string().optional() }),
    creative_skills_list: z.object({}).passthrough(),
    creative_skill_get: z.object({ id: z.enum(CREATIVE_SKILL_IDS) }),
} satisfies Record<ToolName, z.AnyZodObject>;

export const toolDescriptions: Record<ToolName, string> = {
    site_navigate: "跳转网站页面。path 可为 / (首页)、/canvas (我的画布)、/canvas/:id (指定画布)、/image (生图工作台)、/video (视频创作台)、/prompts (提示词库)、/assets (我的素材)、/config (配置)。操作画布前若不在画布页，先用本工具打开画布。",
    canvas_list_projects: "列出用户全部画布（仅标题、创建/更新时间、节点数、连线数，不含完整数据），支持 keyword 搜索和 page/pageSize 分页。返回的 id 可配合 site_navigate 跳转到 /canvas/:id 打开对应画布。",
    canvas_get_state: "读取当前网页画布的节点、连线、选区和视口。",
    canvas_get_selection: "读取当前网页画布选中的节点；文本节点会返回完整可编辑内容。用户说‘这个’或‘选中的节点’时优先调用。",
    canvas_get_node: "按节点 ID 读取单个节点；文本节点会返回完整可编辑内容。先用 canvas_get_state 定位节点，再用本工具读取正文后进行润色、扩写、缩写或迭代。",
    canvas_export_snapshot: "导出当前画布快照，用于理解布局。",
    canvas_apply_ops: "批量操作当前网页画布。ops 支持 add_node、update_node、delete_node、delete_connections、connect_nodes、set_viewport、select_nodes、run_generation。",
    canvas_create_node: "创建任意类型节点：text、image、config、video、audio、director。普通导演台任务优先使用专用的 canvas_create_director_scene。",
    canvas_create_attachment_nodes: "把当前对话中用户上传的图片附件创建成真实画布图片节点。attachmentIds 使用本轮附件清单中的 ID；返回的节点 ID 可传给 canvas_create_generation_flow.referenceNodeIds 作为生成参考图。",
    canvas_create_text_node: "在当前画布创建单个文本节点。",
    canvas_create_text_nodes: "批量创建文本节点，适合生成标题、段落、脚本、说明等内容块。",
    canvas_create_config_node: "创建生成配置节点，可指定 text/image/video/audio 模式和生成参数；Seedance 视频可用 videoReferenceMode=ref/first/firstlast 选择全能参考、首帧或首尾帧；可选择立即触发生成。",
    canvas_create_image_prompt_flow: "创建提示词文本节点和图片生成配置节点，并自动连线，可选择立即触发生图。",
    canvas_create_generation_flow: "创建通用生成流程：提示词文本节点、生成配置节点、参考节点连线，可用于文案、生图、视频或音频。",
    canvas_create_director_scene: "创建三维导演台节点。先用 canvas_get_state 读取当前画布。人物对象使用 primitive=character、role=character 和 characterRig；人物图片通过 sourceNodeId 绑定身份与服装参考，但仍保持 3D 可摆姿态素体。背景图片使用 role=background，并用 backgroundProjection=backdrop 或 panorama；道具/前景素材保留为 image/video 平面。系统会解析媒体并自动连线。不要使用 layers 二维模式，不要手写失效 URL。对象、相机和镜头引用 ID 必须稳定。",
    canvas_update_director_scene: "原地更新现有三维导演台节点。先读取原 director 场景；默认只替换提供字段，replace=true 才整体替换。人物参考图不能覆盖 character 素体或 characterRig；背景要保留 backdrop/panorama 投影。系统会补齐素材连线；不要创建重复导演台。",
    canvas_export_director_prompt: "读取指定导演台节点，把空间调度、镜头段、运镜和关键帧编译成 Seedance 运镜提示词文本节点，并自动连线。",
    canvas_generate_text: "创建通用文本生成流程并立即触发生成。",
    canvas_generate_image: "创建通用图片生成流程并立即触发生成。",
    canvas_generate_video: "创建通用视频生成流程并立即触发生成。",
    canvas_generate_audio: "创建通用音频生成流程并立即触发生成。",
    canvas_update_node: "更新节点基础字段或 metadata。",
    canvas_update_node_text: "原地更新文本节点。text 与 title 至少提供一项；只传 title 时保留正文，只传 text 时保留标题，并始终保留节点 ID、位置和连线。",
    canvas_move_nodes: "移动一个或多个节点，支持绝对坐标或 dx/dy 偏移。",
    canvas_resize_node: "调整节点尺寸。",
    canvas_delete_nodes: "删除指定节点及相关连线。",
    canvas_connect_nodes: "批量连接节点。",
    canvas_select_nodes: "设置当前选中节点。",
    canvas_set_viewport: "调整画布视口。",
    canvas_run_generation: "触发指定节点生成，通常用于配置节点或文本/图片/视频/音频节点。",
    generation_get_status: "查询当前活动网页的生成任务状态。默认返回画布、生图工作台和视频工作台最近任务；可用 scope 过滤来源，用 taskId 查询工作台任务，用 nodeIds 查询画布节点。",
    workbench_image_get_config: "读取生图工作台的当前参数和可选项（可用模型、质量、尺寸/宽高比、张数范围），在调用 workbench_image_generate 前先了解可选值。",
    workbench_image_generate: "在生图工作台填入提示词并按需设置 model、quality、size（如 1:1 或 1024x1024）、count，run 默认 true 会自动点击生成按钮。会自动跳转到生图工作台。生成为异步过程，提交后返回 taskId，可用 generation_get_status 查询状态。",
    workbench_video_get_config: "读取视频创作台的当前参数和可选项（可用模型、尺寸/比例、时长、清晰度/分辨率、是否生成声音与水印）。",
    workbench_video_generate: "在视频创作台填入提示词并按需设置 model、size、seconds、resolution、generateAudio、watermark，run 默认 true 会自动点击生成按钮。会自动跳转到视频创作台。生成为异步过程，提交后返回 taskId，可用 generation_get_status 查询状态。",
    prompts_search: "搜索提示词库（第三方提示词合集），支持 keyword、category、tags 过滤和 page/pageSize 分页，返回标题、提示词、分类、标签、封面等。",
    assets_list: "列出用户「我的素材」，支持 kind（text/image/video）过滤、keyword 搜索和 page/pageSize 分页。为控制体积不返回图片/视频原始 data，仅返回封面与元信息。",
    assets_add: "向「我的素材」新增素材。kind=text 时用 content 传文本内容；kind=image 时用 imageUrl 传图片地址或 dataURL。可附带 title、tags、source、note。",
    creative_skills_list: "列出橙月内置创作 Skill 的 ID、摘要和适用场景，不返回完整规则。需要执行对应任务时再用 creative_skill_get 按 ID 获取，避免无关提示词占用上下文。",
    creative_skill_get: "按 ID 读取一个橙月内置创作 Skill 的完整执行规则、输出契约与固定开源参考来源。仅在当前任务匹配时调用一次。",
};
