export type Position = { x: number; y: number };
export type Viewport = { x: number; y: number; k: number };
export type CanvasNodeType = "image" | "text" | "config" | "video" | "audio" | "director";
export type CanvasNode = { id: string; type: CanvasNodeType; title?: string; position: Position; width: number; height: number; metadata?: Record<string, unknown> };
export type CanvasConnection = { id: string; fromNodeId: string; toNodeId: string };
export type CanvasSnapshot = { projectId?: string; title?: string; nodes?: CanvasNode[]; connections?: CanvasConnection[]; selectedNodeIds?: string[]; viewport?: Viewport; clientId?: string };
export type AgentEmit = (type: string, payload: unknown) => void;
export type AgentAttachment = { id?: string; name?: string; type?: string; size?: number; width?: number; height?: number; dataUrl?: string };

export type DirectorVector3 = [number, number, number];
export type DirectorLayerRole = "background" | "character" | "prop" | "foreground" | "effect";
export type DirectorAssetKind = "image" | "video";
export type DirectorAssetFit = "cover" | "contain";
export type DirectorPrimitive = "character" | "box" | "sphere" | "cylinder" | "cone" | "model" | DirectorAssetKind;
export type DirectorCharacterBodyPreset = "male" | "female" | "strong" | "slim" | "child" | "broad" | "teen" | "chibi";
export type DirectorCharacterPosePreset = "stand" | "t-pose" | "walk" | "run" | "sit" | "crouch" | "kneel" | "double-kneel" | "fight" | "hands-hips" | "hook-punch" | "kick" | "think" | "kick-ball" | "throw" | "bow" | "wave" | "arms-crossed" | "phone" | "point" | "reach" | "custom";
export type DirectorCharacterJoint = "body" | "head" | "leftUpperArm" | "leftForearm" | "rightUpperArm" | "rightForearm" | "leftThigh" | "leftCalf" | "rightThigh" | "rightCalf";
export type DirectorBackgroundProjection = "backdrop" | "panorama";
export type DirectorCharacterRig = {
    bodyPreset: DirectorCharacterBodyPreset;
    posePreset: DirectorCharacterPosePreset;
    height: number;
    width: number;
    joints: Record<DirectorCharacterJoint, DirectorVector3>;
};
export type DirectorStageSettings = {
    showGrid: boolean;
    showGround: boolean;
    showLabels: boolean;
    scenePosition: DirectorVector3;
    sceneRotation: DirectorVector3;
    sceneScale: number;
    panoramaRotation: number;
    panoramaRadius: number;
    ambientIntensity: number;
};
export type DirectorObject = {
    id: string;
    name: string;
    primitive: DirectorPrimitive;
    position: DirectorVector3;
    rotation: DirectorVector3;
    scale: DirectorVector3;
    color: string;
    modelUrl?: string;
    storageKey?: string;
    sourceNodeId?: string;
    assetUrl?: string;
    assetKind?: DirectorAssetKind;
    assetMimeType?: string;
    assetWidth?: number;
    assetHeight?: number;
    displaySize?: [number, number];
    fit?: DirectorAssetFit;
    role?: DirectorLayerRole;
    layerOrder?: number;
    opacity?: number;
    visible?: boolean;
    locked?: boolean;
    characterRig?: DirectorCharacterRig;
    backgroundProjection?: DirectorBackgroundProjection;
};
export type DirectorCamera = { id: string; name: string; position: DirectorVector3; target: DirectorVector3; fov: number };
export type DirectorShot = { id: string; name: string; cameraId: string; start: number; end: number; movement: "static" | "push-in" | "pull-out" | "pan-left" | "pan-right" | "orbit" | "follow"; description?: string };
export type DirectorKeyframe = { id: string; targetType: "object" | "camera"; targetId: string; property: "position" | "rotation" | "scale" | "target" | "fov"; time: number; value: number[] };
export type DirectorScene = {
    version: 2;
    name: string;
    duration: number;
    fps: number;
    aspectRatio: "16:9" | "9:16" | "1:1" | "4:3" | "3:4";
    compositionMode: "layers" | "space3d";
    environment: "studio" | "courtyard" | "mountain" | "desert" | "space";
    background: string;
    stage: DirectorStageSettings;
    objects: DirectorObject[];
    cameras: DirectorCamera[];
    shots: DirectorShot[];
    keyframes: DirectorKeyframe[];
};
